-- Project: SQL Learning Journey
--CODING ORDER

/* SELECT DISTINCT TOP 2
    COL 1,
    COL 2
FROM table
WHERE Col = 10
GROUP BY COL 1
HAVING SUN (COL2) > 30
ORDER BY COL 1 ASC


5) SELECT : Retrieves all columns; DISTINCT: FILTER DUPLICATES
7) TOP: FILTER RESULT ROWS
1) FROM: TELL SQL WHERE TO FIND YOUR DATA
2) WHERE: CONDITION {FILTER ROWS BEFORE AGGREGATION}
3)GROUP BY: COMBINES ROWS WITH SAME VALUE AGGREGATES A COLUMN BY ANOTHER COLUMN
4) HAVING: FILTER ROWS AFTER AGGREGATIONS
6) ORDER BY: ASC (DEFAULT) AND DESC